package com.hcl.paypilot.entity;


import java.time.LocalDate;


import jakarta.persistence.Column;

import jakarta.persistence.Entity;

import jakarta.persistence.GeneratedValue;

import jakarta.persistence.GenerationType;

import jakarta.persistence.Id;

import jakarta.persistence.Table;


/**

* ============================================================================

* Bill Entity

* ============================================================================

*

* This entity represents bill information within the PayPilot

* Application.

*

* The entity stores complete bill management information including:

* - Bill Details

* - Bill Category

* - Due Date

* - Reminder Settings

* - Snooze Details

* - Payment Status

* - Scheduled Payment Configuration

*

* Database Table:

* BILL_TAB

*

* Features Supported:

* - Add Bill

* - Update Bill

* - Delete Bill

* - Bill Reminders

* - Snooze / Unsnooze Bill

* - Scheduled Payments

* - Auto Pay Processing

*

* Author: PayPilot Team

* ============================================================================

*/

@Entity

@Table(name = "BILL_TAB")

public class BillEntity {


    /**

     * Unique identifier for the bill.

     *

     * Automatically generated by the database.

     */

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "bill_id")

    private Long billId;


    /**

     * User identifier associated with the bill.

     */

    @Column(name = "user_id")

    private String userId;


    /**

     * Name of the bill.

     *

     * Examples:

     * - Electricity Bill

     * - Water Bill

     * - Internet Bill

     * - Mobile Recharge

     */

    @Column(name = "bill_name")

    private String billName;


    /**

     * Category of the bill.

     *

     * Examples:

     * - Utilities

     * - Insurance

     * - Subscription

     * - Broadband

     * - Education

     */

    @Column(name = "bill_category")

    private String billCategory;


    /**

     * Total amount to be paid.

     */

    @Column(name = "bill_amount")

    private double billAmount;


    /**

     * Due date for bill payment.

     */

    @Column(name = "bill_due_date")

    private LocalDate billDueDate;


    /**

     * Indicates whether reminders are enabled.

     *

     * Values:

     * - YES

     * - NO

     */

    @Column(name = "reminder_enabled")

    private String reminderEnabled;


    /**

     * Date on which reminder notification

     * should be sent to the user.

     */

    @Column(name = "reminder_date")

    private LocalDate reminderDate;


    /**

     * Current payment status of the bill.

     *

     * Possible Values:

     * - PENDING

     * - PAID

     * - OVERDUE

     * - SNOOZED

     */

    @Column(name = "bill_status")

    private String billStatus;


    /**

     * Snooze expiration date.

     *

     * Used when a bill is temporarily postponed.

     */

    @Column(name = "snooze_date")

    private LocalDate snoozeDate;


    /**

     * Stores the reminder setting before

     * a bill was snoozed.

     *

     * This value is restored when

     * unsnoozing a bill.

     */

    @Column(name = "previousReminderStatus")

    private String previousReminderStatus;


    /**

     * Indicates whether auto payment

     * is enabled for the bill.

     *

     * true  = Scheduled payment enabled

     * false = Scheduled payment disabled

     */

    @Column(name = "shedulePayment")

    private boolean shedulePayment;


    /**

     * Default Constructor.

     */

    public BillEntity() {


    }


    /**

     * Retrieves bill identifier.

     *

     * @return Bill ID

     */

    public Long getBillId() {

        return billId;

    }


    /**

     * Sets bill identifier.

     *

     * @param billId Bill Identifier

     */

    public void setBillId(Long billId) {

        this.billId = billId;

    }


    /**

     * Retrieves user identifier.

     *

     * @return User ID

     */

    public String getUserId() {

        return userId;

    }


    /**

     * Sets user identifier.

     *

     * @param userId User ID

     */

    public void setUserId(String userId) {

        this.userId = userId;

    }


    /**

     * Retrieves bill name.

     *

     * @return Bill Name

     */

    public String getBillName() {

        return billName;

    }


    /**

     * Sets bill name.

     *

     * @param billName Bill Name

     */

    public void setBillName(String billName) {

        this.billName = billName;

    }


    /**

     * Retrieves bill category.

     *

     * @return Bill Category

     */

    public String getBillCategory() {

        return billCategory;

    }


    /**

     * Sets bill category.

     *

     * @param billCategory Bill Category

     */

    public void setBillCategory(String billCategory) {

        this.billCategory = billCategory;

    }


    /**

     * Retrieves bill amount.

     *

     * @return Bill Amount

     */

    public double getBillAmount() {

        return billAmount;

    }


    /**

     * Sets bill amount.

     *

     * @param billAmount Bill Amount

     */

    public void setBillAmount(double billAmount) {

        this.billAmount = billAmount;

    }


    /**

     * Retrieves bill due date.

     *

     * @return Due Date

     */

    public LocalDate getBillDueDate() {

        return billDueDate;

    }


    /**

     * Sets bill due date.

     *

     * @param billDueDate Due Date

     */

    public void setBillDueDate(LocalDate billDueDate) {

        this.billDueDate = billDueDate;

    }


    /**

     * Retrieves reminder enabled status.

     *

     * @return Reminder Status

     */

    public String getReminderEnabled() {

        return reminderEnabled;

    }


    /**

     * Sets reminder enabled status.

     *

     * @param reminderEnabled Reminder Status

     */

    public void setReminderEnabled(String reminderEnabled) {

        this.reminderEnabled = reminderEnabled;

    }


    /**

     * Retrieves reminder date.

     *

     * @return Reminder Date

     */

    public LocalDate getReminderDate() {

        return reminderDate;

    }


    /**

     * Sets reminder date.

     *

     * @param reminderDate Reminder Date

     */

    public void setReminderDate(LocalDate reminderDate) {

        this.reminderDate = reminderDate;

    }


    /**

     * Retrieves bill payment status.

     *

     * @return Bill Status

     */

    public String getBillStatus() {

        return billStatus;

    }


    /**

     * Sets bill payment status.

     *

     * @param billStatus Bill Status

     */

    public void setBillStatus(String billStatus) {

        this.billStatus = billStatus;

    }


    /**

     * Retrieves snooze date.

     *

     * @return Snooze Date

     */

    public LocalDate getSnoozeDate() {

        return snoozeDate;

    }


    /**

     * Sets snooze date.

     *

     * @param snoozeDate Snooze Date

     */

    public void setSnoozeDate(LocalDate snoozeDate) {

        this.snoozeDate = snoozeDate;

    }


    /**

     * Retrieves previous reminder status.

     *

     * Used while restoring reminder settings

     * after unsnoozing a bill.

     *

     * @return Previous Reminder Status

     */

    public String getPreviousReminderStatus() {

        return previousReminderStatus;

    }


    /**

     * Sets previous reminder status.

     *

     * @param previousReminderStatus Previous Reminder Status

     */

    public void setPreviousReminderStatus(

            String previousReminderStatus) {

        this.previousReminderStatus = previousReminderStatus;

    }


    /**

     * Retrieves scheduled payment status.

     *

     * @return true if auto payment enabled

     */

    public boolean isShedulePayment() {

        return shedulePayment;

    }


    /**

     * Sets scheduled payment status.

     *

     * @param shedulePayment Scheduled Payment Flag

     */

    public void setShedulePayment(boolean shedulePayment) {

        this.shedulePayment = shedulePayment;

    }


}
 