package com.hcl.paypilot.entity;


import java.time.LocalDateTime;


import jakarta.persistence.Column;

import jakarta.persistence.Entity;

import jakarta.persistence.GeneratedValue;

import jakarta.persistence.GenerationType;

import jakarta.persistence.Id;

import jakarta.persistence.Table;


/**

* ============================================================================

* Notification Entity

* ============================================================================

*

* This entity represents notification details within the PayPilot

* Application.

*

* Notifications are generated for various user activities such as:

* - Bill payment success

* - Bill reminders

* - Scheduled payment updates

* - Due date alerts

* - Account related activities

*

* The entity is mapped to the database table:

*

* notification_tab

*

* Author: PayPilot Team

* ============================================================================

*/


@Entity

@Table(name = "notification_tab")

public class NotificationEntity {


    /**

     * Unique identifier for the notification.

     *

     * This value is automatically generated by the database.

     */

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "notification_id")

    private Long notificationId;


    /**

     * Unique identifier of the user to whom

     * the notification belongs.

     */

    @Column(name = "user_id", nullable = false)

    private String userId;


    /**

     * Notification message content displayed

     * to the user.

     */

    @Column(name = "notification_message", nullable = false)

    private String notificationMessage;


    /**

     * Indicates whether the notification

     * has been read by the user.

     *

     * Default Value:

     * false

     */

    @Column(name = "is_read")

    private Boolean isRead = false;


    /**

     * Timestamp representing when the

     * notification was created.

     *

     * Default Value:

     * Current system date and time.

     */

    @Column(name = "created_date")

    private LocalDateTime createdDate = LocalDateTime.now();


    /**

     * Default constructor.

     */

    public NotificationEntity() {


    }


    /**

     * Retrieves notification identifier.

     *

     * @return Notification ID

     */

    public Long getNotificationId() {


        return notificationId;


    }


    /**

     * Sets notification identifier.

     *

     * @param notificationId Notification ID

     */

    public void setNotificationId(Long notificationId) {


        this.notificationId = notificationId;


    }


    /**

     * Retrieves user identifier.

     *

     * @return User ID

     */

    public String getUserId() {


        return userId;


    }


    /**

     * Sets user identifier.

     *

     * @param userId User ID

     */

    public void setUserId(String userId) {


        this.userId = userId;


    }


    /**

     * Retrieves notification message.

     *

     * @return Notification Message

     */

    public String getNotificationMessage() {


        return notificationMessage;


    }


    /**

     * Sets notification message.

     *

     * @param notificationMessage Notification Message

     */

    public void setNotificationMessage(

            String notificationMessage) {


        this.notificationMessage = notificationMessage;


    }


    /**

     * Retrieves notification read status.

     *

     * @return true if notification is read,

     *         false otherwise

     */

    public Boolean getIsRead() {


        return isRead;


    }


    /**

     * Updates notification read status.

     *

     * @param isRead Read status

     */

    public void setIsRead(Boolean isRead) {


        this.isRead = isRead;


    }


    /**

     * Retrieves notification creation date.

     *

     * @return Creation date and time

     */

    public LocalDateTime getCreatedDate() {


        return createdDate;


    }


    /**

     * Sets notification creation date.

     *

     * @param createdDate Creation date and time

     */

    public void setCreatedDate(

            LocalDateTime createdDate) {


        this.createdDate = createdDate;


    }


}
 