package com.hcl.paypilot.entity;


import java.time.LocalDateTime;


import jakarta.persistence.Column;

import jakarta.persistence.Entity;

import jakarta.persistence.GeneratedValue;

import jakarta.persistence.GenerationType;

import jakarta.persistence.Id;

import jakarta.persistence.Table;


/**

* ============================================================================

* Payment Entity

* ============================================================================

*

* This entity represents payment information within the PayPilot

* Application.

*

* The entity is used to store payment transaction details generated

* whenever a user pays a bill.

*

* Database Table:

* PAYMENT_TABLE

*

* Maintains:

* - Payment Identifier

* - User Identifier

* - Bill Identifier

* - Paid Amount

* - Payment Date and Time

* - Payment Status

* - Payment Response Message

*

* Example Payment Status Values:

* - SUCCESS

* - FAILED

* - PENDING

*

* Author: PayPilot Team

* ============================================================================

*/

@Entity

@Table(name = "PAYMENT_TABLE")

public class PaymentEntity {


    /**

     * Unique identifier for the payment transaction.

     *

     * Automatically generated by the database.

     */

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "payment_id")

    private Long paymentId;


    /**

     * User identifier associated with

     * the payment transaction.

     */

    @Column(name = "user_id")

    private String userId;


    /**

     * Bill identifier associated with

     * the payment transaction.

     */

    @Column(name = "bill_id")

    private Long billId;


    /**

     * Amount paid towards the bill.

     */

    @Column(name = "paid_amount")

    private Double paidAmount;


    /**

     * Date and time at which the payment

     * transaction was completed.

     */

    @Column(name = "payment_date")

    private LocalDateTime paymentDate;


    /**

     * Current payment status.

     *

     * Possible Values:

     * - SUCCESS

     * - FAILED

     * - PENDING

     */

    @Column(name = "payment_status")

    private String paymentStatus;


    /**

     * Payment response message returned

     * after transaction processing.

     *

     * Examples:

     * - Payment Successful

     * - Payment Failed

     * - Transaction Pending

     */

    @Column(name = "message")

    private String message;


    /**

     * Default Constructor.

     */

    public PaymentEntity() {


    }


    /**

     * Parameterized Constructor.

     *

     * @param paymentId     Payment Identifier

     * @param userId        User Identifier

     * @param billId        Bill Identifier

     * @param paidAmount    Paid Amount

     * @param paymentDate   Payment Date and Time

     * @param paymentStatus Payment Status

     * @param message       Payment Response Message

     */

    public PaymentEntity(

            Long paymentId,

            String userId,

            Long billId,

            Double paidAmount,

            LocalDateTime paymentDate,

            String paymentStatus,

            String message) {


        this.paymentId = paymentId;

        this.userId = userId;

        this.billId = billId;

        this.paidAmount = paidAmount;

        this.paymentDate = paymentDate;

        this.paymentStatus = paymentStatus;

        this.message = message;

    }


    /**

     * Retrieves payment identifier.

     *

     * @return Payment ID

     */

    public Long getPaymentId() {

        return paymentId;

    }


    /**

     * Sets payment identifier.

     *

     * @param paymentId Payment ID

     */

    public void setPaymentId(Long paymentId) {

        this.paymentId = paymentId;

    }


    /**

     * Retrieves user identifier.

     *

     * @return User ID

     */

    public String getUserId() {

        return userId;

    }


    /**

     * Sets user identifier.

     *

     * @param userId User ID

     */

    public void setUserId(String userId) {

        this.userId = userId;

    }


    /**

     * Retrieves bill identifier.

     *

     * @return Bill ID

     */

    public Long getBillId() {

        return billId;

    }


    /**

     * Sets bill identifier.

     *

     * @param billId Bill ID

     */

    public void setBillId(Long billId) {

        this.billId = billId;

    }


    /**

     * Retrieves paid amount.

     *

     * @return Paid Amount

     */

    public Double getPaidAmount() {

        return paidAmount;

    }


    /**

     * Sets paid amount.

     *

     * @param paidAmount Paid Amount

     */

    public void setPaidAmount(Double paidAmount) {

        this.paidAmount = paidAmount;

    }


    /**

     * Retrieves payment date and time.

     *

     * @return Payment Date and Time

     */

    public LocalDateTime getPaymentDate() {

        return paymentDate;

    }


    /**

     * Sets payment date and time.

     *

     * @param paymentDate Payment Date and Time

     */

    public void setPaymentDate(LocalDateTime paymentDate) {

        this.paymentDate = paymentDate;

    }


    /**

     * Retrieves payment status.

     *

     * @return Payment Status

     */

    public String getPaymentStatus() {

        return paymentStatus;

    }


    /**

     * Sets payment status.

     *

     * @param paymentStatus Payment Status

     */

    public void setPaymentStatus(String paymentStatus) {

        this.paymentStatus = paymentStatus;

    }


    /**

     * Retrieves payment response message.

     *

     * @return Payment Message

     */

    public String getMessage() {

        return message;

    }


    /**

     * Sets payment response message.

     *

     * @param message Payment Message

     */

    public void setMessage(String message) {

        this.message = message;

    }


}
 